### ISSUE TITLE
When I update the vscode-icons from 1.9.0 to 1.19.1, this issue happens. The icons are all disappear

### ISSUE THREAD

**Issue by fantasyKing** [robertohuertasm/vscode-icons#281] opened 2016-09-09 09:51 UTC
- I'm using Visual Studio Code Version [1.4.0] [Stable/Insider]

- I'm using the extension version [1.9.1]

- My system is: [OS x] 

- How can this happen ?

![icon-issue](https://cloud.githubusercontent.com/assets/15122256/18382846/55332994-76b5-11e6-8bbc-455f6f0a6929.png)

* When I update the vscode-icons from 1.9.0 to 1.19.1, this issue happens. The icons are all disappear.

**Comment by jens1o** [comment] 2016-09-09 09:52
Please read the README.

You need to enable the icons, so please execute ```Icons Enable```

**Comment by fantasyKing** [comment] 2016-09-09 09:57
I have clicked "icon enabled" and "icon update". But it doesn't work

**Comment by jens1o** [comment] 2016-09-09 09:58
Do you have steps to reproduce?

**Comment by fantasyKing** [comment] 2016-09-09 10:00
NO, I never reproduce anything.

**Comment by jens1o** [comment] 2016-09-09 10:01
You misunderstood. What did you do? Is it a clean install?

**Comment by fantasyKing** [comment] 2016-09-09 10:03
I just click the update btn, it works well before.

**Comment by fantasyKing** [comment] 2016-09-09 10:06
I don't modify any config of this ext

**Comment by jens1o** [comment] 2016-09-09 10:06
Are you behind any proxy?

**Comment by fantasyKing** [comment] 2016-09-09 10:06
yes, I have proxy

**Comment by fantasyKing** [comment] 2016-09-09 10:07
ok, I'll try.

**Comment by jens1o** [comment] 2016-09-09 10:10
Can you check out this issue? https://github.com/robertohuertasm/vscode-icons/issues/21#issuecomment-232577432 Maybe you're done a mistake?

**Comment by leido** [comment] 2016-09-09 10:51
@fantasyKing I have the same issue. here is how I solved it:
1. Make sure you have permission to vscode install folder(/usr/share/code)
2. Icon Update
3. Restart
4. Icon Enable

**Comment by nonoroazoro** [comment] 2016-09-09 11:08
@leido  I've met the same problem right now...

Windows 7 x64, tried vscode 1.4 & 1.5.1, not work.

**Comment by nonoroazoro** [comment] 2016-09-09 11:17
@leido  I've met the same problem right now...

Windows 7 x64, tried vscode 1.4 & 1.5.1, not work.


All right, find out that sometimes the "icons.zip" **could not be downloaded correctly**, which causes the issue.

**Comment by jens1o** [comment] 2016-09-09 12:18
@nonoroazoro Are you behind any proxy? Is there any error in the Dev console?

**Comment by nonoroazoro** [comment] 2016-09-09 13:19
@jens1o  I've tried both with and without proxy, the problem still occurs. After several attempts to update the icons, my vscode downloads the "icons.zip" correctly.
I didn't see any error in the Dev console, but at least it works now. Thanks!

**Comment by fantasyKing** [comment] 2016-09-09 14:15
How to open Dev console? @jens1o

**Comment by fantasyKing** [comment] 2016-09-09 14:25
I solve this problem: "vsicons.icons": "/Users/zhangguojin/programFile/icons.zip" in settings

**Comment by robertohuertasm** [comment] 2016-09-09 14:28
@fantasyKing take into account that you won't be receiving new icons by using this method so you will have to manually update the icons.zip from time to time. The fact that you're not able to download the zip via extension may be due to proxy issues or permission issues. If you feel this issue is solved then please close it.

**Comment by renatomestre** [comment] 2016-09-09 18:44
The last update made my icons desappear.

I tried this but doens't solved:

`"vsicons.icons": "/Users/rmestre/vscode/icons.zip"` (the icons.zip its there!)

**Comment by lachama** [comment] 2016-09-09 23:30
Hey guys, I'm facing the same problem too.

The latest update (v1.5.1) from VSC made my vscode-icons icons dissapear, I'm guessing is related to the fact that on this version we can choose which icons to use from the menu bar as a theme:

<img width="300" alt="bug1" src="https://cloud.githubusercontent.com/assets/9157362/18405770/ac2df710-76ba-11e6-9409-7bc5055c2706.png">
<img width="400" alt="bug2" src="https://cloud.githubusercontent.com/assets/9157362/18405773/b210fa38-76ba-11e6-83c3-231302fba480.png">

The thing is that your vscode-icons sets is not listed on the menu options and I have already installed the extension

**Comment by robertohuertasm** [comment] 2016-09-09 23:46
@lachama, we're preparing a new version with official support (so you will be able to see it also in the file icon theme menu soon). Despite this, we're still supporting the old functionality so you have to unselect whatever icon theme you have selected (select None) and then execute the `icons enable` command. 

Let me know if it works for you.

**Comment by robertohuertasm** [comment] 2016-09-10 09:14
@renatomestre have you solved you issue? Try with the latest extension update 2.0.1

**Comment by robertohuertasm** [comment] 2016-09-10 22:40
@renatomestre, @lachama, @fantasyKing please let us know if you've solved the issue. I will close the issue in case on Monday I have no news from you. :wink:

**Comment by fantasyKing** [comment] 2016-09-12 05:39
@renatomestre ,yes, I'm already fixed it.

**Closed** 2016-09-12 07:20 UTC

**Comment by lachama** [comment] 2016-09-12 14:25
@robertohuertasm sorry I couldn't reply earlier. It's working nicely now ;)

Thanks!

**Comment by renatomestre** [comment] 2016-09-12 16:29
@robertohuertasm its working! Thank u so!
