### ISSUE TITLE
Update extension to File Icon Theme

### ISSUE THREAD

**Issue by SandHilt** [robertohuertasm/vscode-icons#282] opened 2016-09-09 12:12 UTC
**Checklist:**
- I'm using Visual Studio Code Version [1.5.1] [Stable]
- I'm using the extension version [1.x.x]
- [x ] I've regarded to the [FAQ](https://github.com/robertohuertasm/vscode-icons/blob/master/README.md#faqs) and they did not help.
- My system is: [OS] [Windows 10 build 14915]
- [x] I'm sure this issue is not a *duplicate*?
- [ ] I want to create an icon request(if not, remove these lines below):
      - Type: [extension/folder]
      - Icon Name: [name]
      - Sample original Icon(32x32/png/transparent whenever possible): [url]
      - Extensions: .just, .a, .bunch, .of, .extensions
      - [ ] I crossed out "Description", "Steps to reproduce", "Expected behaviour" and "Actual behaviour".

**Description:**

In vscode 1.5(.1), gain ability of change [file icon native](https://code.visualstudio.com/Updates#_workbench).
Please, update to follow new guideline.

[**PLEASE INSERT THE ERROR(S) YOU CAN SEE IN DEV CONSOLE HERE**]

[_Where is the dev console? Launch code, click on "Help" in the menubar at the top, click on "Toggle Developer Tools", and click on that window on "Console"._]

**Steps to reproduce:**
1. First step
2. Second step
3. And you can count yourself, can't you?

_Expected behaviour:_

[these lines are only important if you're submitting an issue]

_Actual behaviour:_

[these lines are only important if you're submitting an issue]

**Comment by jens1o** [comment] 2016-09-09 12:14
We're using the new API, but the new api does not provide all things we have currently.

**Comment by robertohuertasm** [comment] 2016-09-09 13:01
@jens1o we're not still using the new API, we're going to use it and release a new version in the next days.
I'm closing this as this is a duplicate of #177

**Closed by robertohuertasm** 2016-09-09 13:01 UTC
Labels: duplicate
