### ISSUE TITLE
Huge Javascript block icon

### ISSUE THREAD

**Issue by brenoc** [robertohuertasm/vscode-icons#537] opened 2016-12-15 12:48 UTC
I just updated the extension and now the JavaScript icons changed to this huge block of solid bright yellow.
![screen shot 2016-12-15 at 10 42 05 am](https://cloud.githubusercontent.com/assets/284515/21224404/2c131548-c2b3-11e6-9ae1-7409a009fa08.png)

Previously was a much simple and clean one:
![](https://github.com/robertohuertasm/vscode-icons/blob/440e993372e96bd9b6717af8f306c95881c2ba24/icons/file_type_js@2x.png?raw=true)

I think this was introduced 3 days ago by this PR: #520

@robertohuertasm previously said in this issue (#354) that this icon wouldn't happen and I totally agree with him. This icon catches to much attention in the editor.

What made that change happen? I might use another set of icons, because this icon is very intrusive.

**Comment by JimiC** [comment] 2016-12-15 12:49
Duplicate of #514.

**Comment by robertohuertasm** [comment] 2016-12-15 12:50
@brenoc we're releasing the old one again during the week.

**Closed by JimiC** 2016-12-15 12:49 UTC
Labels: duplicate
