### ISSUE TITLE
Admin privileges for VS insiders on mac

### ISSUE THREAD

**Issue by gsaadeh** [robertohuertasm/vscode-icons#80] opened 2016-07-12 17:56 UTC
<img width="1194" alt="capture" src="https://cloud.githubusercontent.com/assets/3935786/16777613/0ee0a65c-481f-11e6-8497-f6858864a69b.png">

Currently getting this error when trying to run "Icons Enable" in vscode insiders build (1.4.0) on a mac.

**Comment by robertohuertasm** [comment] 2016-07-12 17:57
This is a duplicate of #79

**Closed by robertohuertasm** 2016-07-12 17:57 UTC
Labels: duplicate

**Comment by robertohuertasm** [comment] 2016-07-13 12:03
I've recently pushed v.1.4.0 and it should be working now 👍

**Comment by gsaadeh** [comment] 2016-07-13 12:13
Thank you Roberto, I can confirm that is working now. Great stuff!
