### ISSUE TITLE
Icon Request: dart

### ISSUE THREAD

**Issue by DrecDroid** [robertohuertasm/vscode-icons#206] opened 2016-08-28 00:41 UTC

**Comment by robertohuertasm** [comment] 2016-08-28 00:58
@DrecDroid please, read the contribution guide before submitting and icon request :wink:. 

You've submitted a duplicate of [186](https://github.com/robertohuertasm/vscode-icons/issues/186) which is already implemented and waiting to be released.

**Closed by robertohuertasm** 2016-08-28 00:58 UTC
Labels: duplicate
