### ISSUE TITLE
Wrong icon for 'license.js'

### ISSUE THREAD

**Issue by flxbe** [robertohuertasm/vscode-icons#557] opened 2016-12-19 17:22 UTC
Hey

when naming a file `license.js`, the license-icon is used. When using `license.spec.js`, the correct icon is displayed. Is this behavior expected? In my case, the js-icon would have been the correct one.

<img width="190" alt="bildschirmfoto 2016-12-19 um 18 09 36" src="https://cloud.githubusercontent.com/assets/9663231/21321933/2d4a97bc-c617-11e6-996a-cbe7317f0b78.png">

#### Some additional information:
vscode: 1.8.0
vscode-icons: 4.2.0

**Comment by JimiC** [comment] 2016-12-19 18:01
@robertohuertasm `filename` overrides `languageId`
![screenshot - 19_12_2016 19_59_12](https://cloud.githubusercontent.com/assets/1716442/21323409/f9f32cc6-c625-11e6-8935-0bf0fc0fd9d6.png)

**Comment by robertohuertasm** [comment] 2016-12-19 18:40
@JimiC I was aware of that but didn't expect this greedy behavior. This seems like a bug in VSCode to me. Filename classes should only be added to files with the exact match. cc @aeschli, maybe you can give us a hand here. Is this the expected behavior?

**Comment by JimiC** [comment] 2016-12-19 18:42
@robertohuertasm I know you knew. Just wanted to point out the cause.

**Comment by robertohuertasm** [comment] 2016-12-19 18:50
It seems that only happens with filenames that have no extension. Of course, we haven't had this issue before because we were mainly using file extensions. 
I'm going to raise an issue in vscode's repo about this.

**Comment by robertohuertasm** [comment] 2016-12-28 01:17
I've also submitted a [PR #17865](https://github.com/Microsoft/vscode/issues/17865)

**Comment by robertohuertasm** [comment] 2016-12-31 02:15
It seems that the PR has been merged! :+1:

**Comment by jens1o** [comment] 2017-01-01 10:25
What does this mean for us? Do we have to fix anything or do we need to wait for the next update?

**Comment by JimiC** [comment] 2017-01-01 10:29
The next `vscode` will be in a few days (January release). We could wait a bit or close it. If somebody opens another issue we could point him/her to the right direction.

**Comment by robertohuertasm** [comment] 2017-01-01 13:09
I didn't close it just to wait for the new functionality to be deployed and test it again just in case.

**Comment by robertohuertasm** [comment] 2017-01-08 11:30
I've checked this in the `Insiders version` and it works so I'm closing this.

**Closed by robertohuertasm** 2017-01-08 11:30 UTC
Labels: bug, vscode official integration

**Comment by JimiC** [comment] 2017-01-08 11:31
Confirming.
