### ISSUE TITLE
Server returned 404

### ISSUE THREAD

**Issue by Moncef12** [robertohuertasm/vscode-icons#15] opened 2016-06-04 13:16 UTC
Hi, 

I'm getting: "Server returned 404" , when launching the command (ctrl+p => ext install vscode-icons)  to install this extension.

(I'm on linux/ubuntu).

**Comment by robertohuertasm** [comment] 2016-06-05 09:17
Hi @Moncef12, have you checked your internet connection? I've just tested it with a new Ubuntu machine and it worked fine. This issue of yours is not related to the extension but to the VS Code marketplace. It's Microsoft who provides the package.

Please, try it again and let me know what you find. :wink:

**Comment by robertohuertasm** [comment] 2016-06-05 20:52
@Moncef12 any news on this?

**Comment by Moncef12** [comment] 2016-06-06 07:16
@robertohuertasm : the same problem, I will upgrade to the last version of vscode today and try again.

**Comment by robertohuertasm** [comment] 2016-06-06 08:44
Ok. Let me know how it ends so I can close the issue. :wink:

**Comment by Meerownymous** [comment] 2016-06-07 08:10
Same problem for me - If i open ctrl+p and enter the command, VS doesn't find your repo and only suggests some other ones.

**Comment by robertohuertasm** [comment] 2016-06-07 08:24
@Meerownymous what's the version you have installed? Uninstall it and reinstall it again.f I've tested it in Windows, Ubuntu and OS X and I can't reproduce this behaviour.

**Comment by Meerownymous** [comment] 2016-06-07 08:48
Visual Studio Version 1.2.0, build from yesterday.
I figured out that putting the module name in quotes solves the listing problem: ext install "vscode-icons" - I guess that vscode otherwise treats it as two words.

The extension version is 1.0.20

**Comment by robertohuertasm** [comment] 2016-06-07 09:06
@Meerownymous thank you very much for your findings! It seems that vscode maybe a very common term in all the extensions and as you said, vscode treats the search as two different words. In fact, if you try ext install icons it shows you the extension right away. If you put ext install vscode-icons it does appear, but listed down in the scroll.

Anyway, this doesn't seem to be the same problem that @Moncef12 reported. @Moncef12 do you have any news on this?

**Comment by Moncef12** [comment] 2016-06-07 12:26
It works !! I'm on the last version 1.2. (I was on a really old version 0.10 ...)

Thank you very much  !!

**Closed** 2016-06-07 14:43 UTC
